/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package contactos_amigos;

import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.lang.NumberFormatException;
import javax.swing.ImageIcon;

public class VentanaPrincipal extends javax.swing.JFrame {


   
    public VentanaPrincipal() {
        initComponents();
        this.setTitle("Contactos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRead = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMensaje = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btnCreate.setText("Crear");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnDelete.setText("Borrar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnRead.setText("Leer");
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });

        btnUpdate.setText("Actualizar");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("Nombre");

        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("Numero");

        txtMensaje.setForeground(new java.awt.Color(204, 255, 204));

        txtImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/directorio-telefonico (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(txtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(txtMensaje))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnCreate)
                        .addGap(18, 18, 18)
                        .addComponent(btnRead)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(txtImagen))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(txtMensaje)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnRead)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
    
     try {
        String newName = txtNombre.getText().strip();
        long newNumber = Long.parseLong(txtNumero.getText().strip());
        String contacto; 
        String name;
        long number;
        File file = new File("C:\\Users\\LENOVO\\Desktop\\Programacion\\Actividad 6\\friendContact.txt");
        
        if (!file.exists()){
            file.createNewFile();
        }
        
        RandomAccessFile raf = new RandomAccessFile(file, "rw");
        boolean found = false;
        
        while (raf.getFilePointer() < raf.length()) {
            contacto = raf.readLine();
            String[] lineSplit = contacto.split(":");
            name = lineSplit[0];
            number = Long.parseLong(lineSplit[1]);
            if (name.equalsIgnoreCase(newName) || number == newNumber) {
                found = true;
                break;
            }
        }
        
        if (!found) {
            raf.seek(raf.length());
            if (raf.length() > 0) {
                raf.writeBytes(System.lineSeparator()); 
            }
            contacto = newName + ":" + String.valueOf(newNumber);
            raf.writeBytes(contacto);
            txtMensaje.setText("Contacto agregado");
            raf.close();
            txtImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/agregar-usuario.png")));
        } else {
            raf.close();
            txtMensaje.setText("Nombre o Numero ya existente");
            txtImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/signo.png")));
        }
    } catch (IOException ioe) {
        txtMensaje.setText("Problemas con el archivo indicado");
        System.out.println(ioe);
        txtImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/error.png")));
    } catch (NumberFormatException nef) {
        txtMensaje.setText("Nombre y/o numero invalido");
        System.out.println(nef);
        txtImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/error.png")));
    }
    
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
    try {
    String deleteName = txtNombre.getText().strip();
    String deleteNumber = txtNumero.getText().strip();
    File file = new File("C:\\Users\\LENOVO\\Desktop\\Programacion\\Actividad 6\\friendContact.txt");

    if (!file.exists()) {
        file.createNewFile();
    }

    File tempFile = new File("C:\\Users\\LENOVO\\Desktop\\Programacion\\Actividad 6\\temp.txt");
    RandomAccessFile raf = new RandomAccessFile(file, "rw");
    RandomAccessFile tmpRaf = new RandomAccessFile(tempFile, "rw");

    boolean found = false;

    while (raf.getFilePointer() < raf.length()) {
        String nameNumberString = raf.readLine();
        if (nameNumberString == null) {
            break; 
        }

        String[] lineSplit = nameNumberString.split(":");
        if (lineSplit.length != 2) {
            continue;
        }

        String name = lineSplit[0].trim();
        String number = lineSplit[1].trim();

        if (name.equalsIgnoreCase(deleteName)) {
            found = true;
            continue; 
        }

        if (!name.isEmpty()) {
            tmpRaf.writeBytes(name + ":" + number);
            tmpRaf.writeBytes(System.lineSeparator());
        }
    }

    raf.close();
    tmpRaf.close();

    if (found) {
        file.delete();
        tempFile.renameTo(file);
        
        RandomAccessFile finalRaf = new RandomAccessFile(file, "rw");
        finalRaf.setLength(finalRaf.length() - 2); 
        finalRaf.close();

        txtMensaje.setText("Amigo eliminado");
        txtImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/eliminado.png")));
    } else {
        tempFile.delete(); 
        txtMensaje.setText("El amigo no existe");
        txtImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/no_found.png")));
    }
} catch (IOException e) {
    txtMensaje.setText("Problemas con el archivo indicado");
    System.out.println(e);
    txtImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/error.png")));
}
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        
    try {
        String searchName = txtNombre.getText().strip();
        String nameNumberString;
        String name;
        long number;
       

        File file = new File("C:\\Users\\LENOVO\\Desktop\\Programacion\\Actividad 6\\friendContact.txt");

        if (!file.exists()) {
            file.createNewFile(); }
        
        boolean found = false;
        RandomAccessFile raf = new RandomAccessFile(file, "rw");

        while (raf.getFilePointer() < raf.length()) {
            nameNumberString = raf.readLine();
            String[] lineSplit = nameNumberString.split(":");
            name = lineSplit[0];
            number = Long.parseLong(lineSplit[1]);

            if (name.equalsIgnoreCase(searchName)) {
                found = true;
                txtImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/found.png")));
                txtMensaje.setText("El numero de '" + name + "' es '" + number + "'");
                break;
            }
        }

        if (!found) {
            txtImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/no_found.png")));
            txtMensaje.setText("Este contacto no existe");
        }

        raf.close();
    } catch (IOException ioe) {
        txtMensaje.setText("Problemas con el archivo indicado");
        txtImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/error.png")));
        System.out.println(ioe);
    } catch (NumberFormatException nef) {
        txtMensaje.setText("Numero invalido en el archivo");
        txtImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/error.png")));
        System.out.println(nef); }      
    }//GEN-LAST:event_btnReadActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
       
    try {
    String updateName = txtNombre.getText().strip();
    long updateNumber = Long.parseLong(txtNumero.getText().strip());
    String contacto;
    String name;
    int index;
    File file = new File("C:\\Users\\LENOVO\\Desktop\\Programacion\\Actividad 6\\friendContact.txt");
    if (!file.exists()) {
        file.createNewFile();
    }
    File tmpFile = new File("C:\\Users\\LENOVO\\Desktop\\Programacion\\Actividad 6\\temp.txt");
    RandomAccessFile raf = new RandomAccessFile(file, "rw");
    RandomAccessFile tmpraf = new RandomAccessFile(tmpFile, "rw");
    boolean found = false;

    while (raf.getFilePointer() < raf.length()) {
        contacto = raf.readLine();
        index = contacto.indexOf(':');
        name = contacto.substring(0, index);
        if (name.toLowerCase().equals(updateName.toLowerCase())) {
            contacto = name + ":" + String.valueOf(updateNumber);
            found = true; // Se encontró el contacto
        }
        tmpraf.writeBytes(contacto);
        tmpraf.writeBytes(System.lineSeparator());
    }

    raf.seek(0);
    tmpraf.seek(0);

    while (tmpraf.getFilePointer() < tmpraf.length()) {
        raf.writeBytes(tmpraf.readLine());
        raf.writeBytes(System.lineSeparator());
    }

    raf.setLength(tmpraf.length());

    tmpraf.close();
    raf.close();

    tmpFile.delete();

    if (found) {
        txtImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/carga.png")));
        txtMensaje.setText("Amigo actualizado");
    } else {
        txtImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/no_found.png")));
        txtMensaje.setText("El contacto no existe");
    }
} catch (IOException ioe) {
    txtMensaje.setText("Problemas con el archivo indicado");
    txtImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/error.png")));
    System.out.println(ioe);
} catch (NumberFormatException nef) {
    txtMensaje.setText("Nombre y/o numero invalido");
    txtImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/error.png")));
    System.out.println(nef);
}  
        
    }//GEN-LAST:event_btnUpdateActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtImagen;
    private javax.swing.JLabel txtMensaje;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
